---
all:
  hosts:
    asw_test:
      ansible_host: 10.113.103.220
      ansible_user: gavsnetwork
      ansible_password: "Admin@!@#45678"
      ansible_network_os: junipernetworks.junos.junos
      ansible_connection: ansible.netcommon.netconf
      ansible_port: 830
      ansible_command_timeout: 120
      ansible_connect_timeout: 60