---
all:
  children:
    mexico_access_switches:
      hosts:
        FSMEXICOASW01:
          ansible_host: 10.0.0.11   # CHANGE ME
        FSMEXICOASW02:
          ansible_host: 10.0.0.12   # CHANGE ME
