---
- name: Consultar información en un switch Juniper
  gather_facts: yes
  hosts: all
  tasks:
    - name: Obtener versión del sistema
      junipernetworks.junos.junos_command:
        commands:
          - show version
      register: version_output

    - name: Mostrar resultado
      debug:
        var: version_output

    - name: Obtener información de interfaces
      junipernetworks.junos.junos_command:
        commands:
          - show interfaces terse
      register: interfaces_output

    - name: Mostrar interfaces
      debug:
        var: interfaces_output
